### ISSUE TITLE
Update to Jest 18

### ISSUE THREAD

**Issue by luizbon** [adalbertoteixeira/jest-bamboo-formatter#2]
After upgrading to Jest 18 I got this error:
```
Error: Jest: Module "node_modules/jest-bamboo-formatter" in the "testResultsProcessor" option was not found.
    at resolve (.\node_modules\jest-config\build\normalize.js:48:11)
    at Object.keys.reduce.e (.\node_modules\jest-config\build\normalize.js:343:17)
    at Array.reduce (native)
    at normalize .\node_modules\jest-config\build\normalize.js:294:23)
    at promisify.then.data (.\node_modules\jest-config\build\loadFromFile.js:30:12)
```

**Comment by leonardodavila** [comment]
Fixed?

**Comment by MartinHaeusler** [comment]
Same here!

**Comment by nemesv** [comment]
For me adding the `<rootDir>` to the path **fixed the problem** when using when I got the same error for the jest-trx-results-processor processor: 
```
"testResultsProcessor": "<rootDir>/node_modules/jest-bamboo-formatter",
```

**Comment by ramzgt** [comment]
I tried the solution suggested by @nemesv.

Did not work for me.

Note I am running Jest through Powershell in Win10.
